### ISSUE TITLE
Line number 3.14 does not work

### ISSUE THREAD

**Issue by Thatguyonfire240** [PQCraft/clibasic#8]
### Steps to reproduce:
Try to use line number 3.14

### Expected behavior:
Line number 3.14 does not appear

### Actual behavior:
Clibasic gives error

**Comment by PQCraft** [comment]
From the manual under 'Syntax':
> An whole number greater or equal to 0 may be prefixed before a command to indicate a line number.

A decimal is not a whole number, closing.
