### ISSUE TITLE
Faster alternative to _kbhit()

### ISSUE THREAD

**Issue by PQCraft** [PQCraft/CLIBASIC#9]
The Windows version of CLIBASIC runs slower than the Linux version due to the _kbhit() function taking forever. If anyone knows a faster way to check if there are characters in the STDIN buffer, please let me know.

**Comment by PQCraft** [comment]
I have seen that Windows make have ioctl, I am looking into using that instead

**Comment by PQCraft** [comment]
welp nvm

**Comment by PQCraft** [comment]
not in mingw

**Comment by argvsc47** [comment]
try using assembly lol

**Comment by argvsc47** [comment]
hmmmm

**Comment by argvsc47** [comment]
can't you replace the Api call with something of your own
(sorry if this seems unhelpful but i like reinventing the wheel so most of my ideas are like this)

**Comment by integral-sketch** [comment]
You are looking for the `GetAsyncKeyState()` function.

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getasynckeystate

**Comment by integral-sketch** [comment]
Try compiling with Clang.

**Comment by PQCraft** [comment]
@integral-sketch I ended up using Windows threads to solve this (I may switch it to POSIX) and running _kbhit() separately from the main thread. I am leaving this issue open though to see if anyone comes up with a better way or my way fails (I have to sort out some problems with locking that cause the program to deadlock under WINE but not under Windows which means it probably could deadlock under Windows but it somehow missed (I'm guessing it's due to the differences in how Linux/WINE and Windows schedule))

**Comment by PQCraft** [comment]
I have actually been sitting on releasing CLIBASIC 1.0 for some time now due to coming up with the brilliant idea of making a 3D engine at the same time lol

**Comment by integral-sketch** [comment]
> @integral-sketch I ended up using Windows threads to solve this (I may switch it to POSIX) and running _kbhit() separately from the main thread. I am leaving this issue open though to see if anyone comes up with a better way or my way fails (I have to sort out some problems with locking that cause the program to deadlock under WINE but not under Windows which means it probably could deadlock under Windows but it somehow missed (I'm guessing it's due to the differences in how Linux/WINE and Windows schedule))

What’s the performance gain of opening a new thread? Windows has a *very* large cold-start to opening a new thread and putting `lock` everywhere isn’t going to help. The reason why WINE is failing is because it has to make more kernel calls to switch cores unnecessarily like Windows does. WIN will switch threads to separate cores which has very high latency, so I highly advise you find some other method. Then again, nothing better, right? Just port it Bash.

**Comment by integral-sketch** [comment]
It seems as if WINE's implementation of `_kbhit` is not ideal. Check it out for yourself, maybe you could do a patch:

https://fossies.org/dox/wine-6.22/conio_8h.html

**Comment by integral-sketch** [comment]
```c
int CDECL _kbhit(void)
{
  int retval = 0;
 
  LOCK_CONSOLE;
  if (__MSVCRT_console_buffer != EOF)
    retval = 1;
  else
  {
    /* FIXME: There has to be a faster way than this in Win32.. */
    INPUT_RECORD *ir = NULL;
    DWORD count = 0, i;
 
    GetNumberOfConsoleInputEvents(msvcrt_input_console(), &count);
 
    if (count && (ir = malloc(count * sizeof(INPUT_RECORD))) &&
        PeekConsoleInputA(msvcrt_input_console(), ir, count, &count))
      for(i = 0; i < count - 1; i++)
      {
        if (ir[i].EventType == KEY_EVENT &&
            ir[i].Event.KeyEvent.bKeyDown &&
            ir[i].Event.KeyEvent.uChar.AsciiChar)
        {
          retval = 1;
          break;
        }
      }
    free(ir);
  }
  UNLOCK_CONSOLE;
  return retval;
}
```

There are a few obvious reasons why this is a really shitty and slow implementation. You are allocating and then freeing memory for every call you get, as well as calling the `PeekConsoleInputA` function, which is notorious for being slow.

**Comment by integral-sketch** [comment]
Under the hood mem allocations are not good at all, and then we have this very amazing and beautiful for loop that's not slow at all obviously.

**Comment by PQCraft** [comment]
> What’s the performance gain of opening a new thread? Windows has a _very_ large cold-start to opening a new thread and putting `lock` everywhere isn’t going to help. The reason why WINE is failing is because it has to make more kernel calls to switch cores unnecessarily like Windows does. WIN will switch threads to separate cores which has very high latency, so I highly advise you find some other method. Then again, nothing better, right? Just port it Powershell.

@integral-sketch Well CLIBASIC already has a pretty long startup time due to readline making numerous calls to malloc() and just CLIBASIC in general being unoptimized and clunky. WINE only fails sometimes. As far as I can tell it's random when it will freeze so I don't think that is the reason it would be failing as that would probably be more consistent. _kbhit() is slow on Windows too. I have tested it. I have a speed test .bas program (it's `speedtestfast.bas` in `examples/`) that show how many times it can increment a variable in 5 seconds. On Linux I get something around 1500000 while on Windows, it was a dismal 4000. After moving the keyboard polling code to a seperate thread, the scores were basically identical with Windows being around 1400000. Also, wdym by 'Just port it Powershell'? If you mean port the entirety of CLIBASIC to Powershell then I politely decline as that would take ages and I hate Powershell syntax and would gladly take C and Sh over anything. Also Powershell is interpreted so I don't think that would run very well.

**Comment by integral-sketch** [comment]
> > What’s the performance gain of opening a new thread? Windows has a _very_ large cold-start to opening a new thread and putting `lock` everywhere isn’t going to help. The reason why WINE is failing is because it has to make more kernel calls to switch cores unnecessarily like Windows does. WIN will switch threads to separate cores which has very high latency, so I highly advise you find some other method. Then again, nothing better, right? Just port it Powershell.
> 
> @integral-sketch Well CLIBASIC already has a pretty long startup time due to readline making numerous calls to malloc() and just CLIBASIC in general being unoptimized and clunky. WINE only fails sometimes. As far as I can tell it's random when it will freeze so I don't think that is the reason it would be failing as that would probably be more consistent. _kbhit() is slow on Windows too. I have tested it. I have a speed test .bas program (it's `speedtestfast.bas` in `examples/`) that show how many times it can increment a variable in 5 seconds. On Linux I get something around 1500000 while on Windows, it was a dismal 4000. After moving the keyboard polling code to a seperate thread, the scores were basically identical with Windows being around 1400000. Also, wdym by 'Just port it Powershell'? If you mean port the entirety of CLIBASIC to Powershell then I politely decline as that would take ages and I hate Powershell syntax and would gladly take C and Sh over anything. Also Powershell is interpreted so I don't think that would run very well.

The powershell port thing was a joke...

**Comment by integral-sketch** [comment]
> I have tested the new solution and have decided it works 👍

Just moving it to a new thread?

**Comment by PQCraft** [comment]
> > I have tested the new solution and have decided it works +1
> 
> Just moving it to a new thread?

@integral-sketch Yes. I used pthreads and it has a few functions to init, start, and stop the thread. I suspend the thread when reading keys, using readline(), or starting processes.
